<?xml version="1.0" encoding="UTF-8"?>
<!--
Detailed configuration of the WMS service.  This config file can be used to
set default styling parameters for each dataset/variable, and to enable or disable
the GetFeatureInfo operation.

See http://www.resc.reading.ac.uk/trac/myocean-tools/wiki/WmsDetailedConfiguration
for more information.
-->
<!DOCTYPE wmsConfig [

<!ELEMENT wmsConfig (global, overrides?)>

<!ELEMENT global (defaults, standardNames?)>

<!ELEMENT defaults (allowFeatureInfo, defaultColorScaleRange, defaultPaletteName, defaultNumColorBands, logScaling)>

<!ELEMENT standardNames (standardName*)>

<!ELEMENT standardName (defaultColorScaleRange?, defaultPaletteName?, defaultNumColorBands?, logScaling?)>
<!ATTLIST standardName name CDATA #REQUIRED>
<!ATTLIST standardName units CDATA #REQUIRED>

<!ELEMENT overrides (datasetPath*)>

<!ELEMENT datasetPath (pathDefaults?, variables?)>
<!ATTLIST datasetPath pathSpec CDATA #REQUIRED>

<!ELEMENT pathDefaults (allowFeatureInfo?, defaultColorScaleRange?, defaultPaletteName?, defaultNumColorBands?, logScaling?)>

<!ELEMENT variables (variable*)>

<!ELEMENT variable (defaultColorScaleRange?, defaultPaletteName?, defaultNumColorBands?, logScaling?, title?, abstract?, range?, gamma?, red?, green?, blue?)>
<!ATTLIST variable id CDATA #REQUIRED>

<!ELEMENT allowFeatureInfo (#PCDATA)>
<!ELEMENT defaultColorScaleRange (#PCDATA)>
<!ELEMENT defaultPaletteName (#PCDATA)>
<!ELEMENT defaultNumColorBands (#PCDATA)>
<!ELEMENT logScaling (#PCDATA)>

<!-- false colour -->
<!ELEMENT title (#PCDATA)>
<!ELEMENT abstract (#PCDATA)>
<!ELEMENT range (#PCDATA)>
<!ELEMENT gamma (#PCDATA)>
<!ELEMENT red (source, range?, gamma?)>
<!ELEMENT green (source, range?, gamma?)>
<!ELEMENT blue (source, range?, gamma?)>
<!ELEMENT source (#PCDATA)>
]>
<wmsConfig>

    <global>
        <!-- These settings apply to all datasets unless overridden below -->

        <defaults>
            <!-- The global defaults. All elements are mandatory -->
            <allowFeatureInfo>true</allowFeatureInfo>
            <defaultColorScaleRange>-50 50</defaultColorScaleRange>
            <defaultPaletteName>rainbow</defaultPaletteName>
            <defaultNumColorBands>20</defaultNumColorBands>
            <logScaling>false</logScaling>
        </defaults>

    </global>

    <overrides>

        <datasetPath pathSpec="laamu/*.nc">
            <pathDefaults>
                <defaultColorScaleRange>0.5 255.5</defaultColorScaleRange>
                <defaultPaletteName>greyscale</defaultPaletteName>
                <defaultNumColorBands>252</defaultNumColorBands>
                <logScaling>false</logScaling>
            </pathDefaults>
            <variables>
                <variable id="False741">
                    <defaultColorScaleRange>0.5 252.5</defaultColorScaleRange>
                    <defaultPaletteName>rgb252</defaultPaletteName>
                </variable>
                <variable id="FalseColour741">
                    <red>
                        <source>Band7</source>
                    </red>
                    <green>
                        <source>Band4</source>
                    </green>
                    <blue>
                        <source>Band1</source>
                    </blue>
                </variable>
            </variables>
        </datasetPath>

        <datasetPath pathSpec="adelaide/*.nc">
            <pathDefaults>
                <defaultColorScaleRange>1 65535</defaultColorScaleRange>
                <defaultPaletteName>greyscale</defaultPaletteName>
                <defaultNumColorBands>252</defaultNumColorBands>
                <logScaling>false</logScaling>
            </pathDefaults>
            <variables>
                <variable id="FalseColour741">
                    <title>False Colour</title>
                    <abstract>False Colour from bands 7, 4, and 1</abstract>
                    <range>1 10000</range>
                    <gamma>0.5</gamma>
                    <red>
                        <source>Band7</source>
                    </red>
                    <green>
                        <source>Band4</source>
                    </green>
                    <blue>
                        <source>Band1</source>
                    </blue>
                </variable>
            </variables>
        </datasetPath>

    </overrides>

</wmsConfig>
